package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

/**
 * Academy generated by hbm2java
 */
public class Academy implements java.io.Serializable {

	private Integer id;
	private String academyCode;
	private String academyName;
	private String schoolCode;

	public Academy() {
	}

	public Academy(String academyCode, String academyName, String schoolCode) {
		this.academyCode = academyCode;
		this.academyName = academyName;
		this.schoolCode = schoolCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAcademyCode() {
		return this.academyCode;
	}

	public void setAcademyCode(String academyCode) {
		this.academyCode = academyCode;
	}

	public String getAcademyName() {
		return this.academyName;
	}

	public void setAcademyName(String academyName) {
		this.academyName = academyName;
	}

	public String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

}
