package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer id;
	private String classNo;
	private String major;
	private String academyCode;

	public Classes() {
	}

	public Classes(String classNo, String major, String academyCode) {
		this.classNo = classNo;
		this.major = major;
		this.academyCode = academyCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getAcademyCode() {
		return this.academyCode;
	}

	public void setAcademyCode(String academyCode) {
		this.academyCode = academyCode;
	}

}
