package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Loginlog generated by hbm2java
 */
public class Loginlog implements java.io.Serializable {

	private Long id;
	private String userName;
	private String osname;
	private String browserName;
	private String loginIp;
	private Date loginTime;
	private long uid;

	public Loginlog() {
	}

	public Loginlog(String userName, String loginIp, Date loginTime, long uid) {
		this.userName = userName;
		this.loginIp = loginIp;
		this.loginTime = loginTime;
		this.uid = uid;
	}

	public Loginlog(String userName, String osname, String browserName,
			String loginIp, Date loginTime, long uid) {
		this.userName = userName;
		this.osname = osname;
		this.browserName = browserName;
		this.loginIp = loginIp;
		this.loginTime = loginTime;
		this.uid = uid;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getOsname() {
		return this.osname;
	}

	public void setOsname(String osname) {
		this.osname = osname;
	}

	public String getBrowserName() {
		return this.browserName;
	}

	public void setBrowserName(String browserName) {
		this.browserName = browserName;
	}

	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public long getUid() {
		return this.uid;
	}

	public void setUid(long uid) {
		this.uid = uid;
	}

}
