package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

/**
 * Menuitem generated by hbm2java
 */
public class Menuitem implements java.io.Serializable {

	private Integer id;
	private String menuId;
	private String menuItemName;
	private String menuItemUrl;
	private String parentId;
	private int status;
	private String menuItemDes;
	private int authority;
	private Integer sort;

	public Menuitem() {
	}

	public Menuitem(String menuId, String menuItemName, int status,
			int authority) {
		this.menuId = menuId;
		this.menuItemName = menuItemName;
		this.status = status;
		this.authority = authority;
	}

	public Menuitem(String menuId, String menuItemName, String menuItemUrl,
			String parentId, int status, String menuItemDes, int authority,
			Integer sort) {
		this.menuId = menuId;
		this.menuItemName = menuItemName;
		this.menuItemUrl = menuItemUrl;
		this.parentId = parentId;
		this.status = status;
		this.menuItemDes = menuItemDes;
		this.authority = authority;
		this.sort = sort;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getMenuItemName() {
		return this.menuItemName;
	}

	public void setMenuItemName(String menuItemName) {
		this.menuItemName = menuItemName;
	}

	public String getMenuItemUrl() {
		return this.menuItemUrl;
	}

	public void setMenuItemUrl(String menuItemUrl) {
		this.menuItemUrl = menuItemUrl;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getMenuItemDes() {
		return this.menuItemDes;
	}

	public void setMenuItemDes(String menuItemDes) {
		this.menuItemDes = menuItemDes;
	}

	public int getAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

}
