package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private Integer id;
	private String title;
	private String substance;
	private int status;
	private Date publishTime;

	public Notice() {
	}

	public Notice(String substance, int status, Date publishTime) {
		this.substance = substance;
		this.status = status;
		this.publishTime = publishTime;
	}

	public Notice(String title, String substance, int status, Date publishTime) {
		this.title = title;
		this.substance = substance;
		this.status = status;
		this.publishTime = publishTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubstance() {
		return this.substance;
	}

	public void setSubstance(String substance) {
		this.substance = substance;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

}
