package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

	private Integer id;
	private String schoolCode;
	private String schoolName;

	public School() {
	}

	public School(String schoolCode, String schoolName) {
		this.schoolCode = schoolCode;
		this.schoolName = schoolName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

}
