package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private String studentNo;
	private String studentName;
	private String classNo;
	private String sex;
	private Date birth;
	private String idCard;
	private String telPhone;

	public Student() {
	}

	public Student(String studentNo, String studentName, String classNo,
			String sex, Date birth, String idCard, String telPhone) {
		this.studentNo = studentNo;
		this.studentName = studentName;
		this.classNo = classNo;
		this.sex = sex;
		this.birth = birth;
		this.idCard = idCard;
		this.telPhone = telPhone;
	}

	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public String getClassNo() {
		return this.classNo;
	}

	public void setClassNo(String classNo) {
		this.classNo = classNo;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

}
