package com.lin.lostandfound.model;

// Generated 2017-4-20 10:53:03 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long id;
	private String userName;
	private String password;
	private String grade;
	private String name;
	private String nickName;
	private String telPhone;
	private String email;
	private String qq;
	private int state;
	private Date createTime;
	private int isNew;
	private Date lastLoginTime;

	public User() {
	}

	public User(String userName, String password, String grade,
			String telPhone, int state, Date createTime, int isNew) {
		this.userName = userName;
		this.password = password;
		this.grade = grade;
		this.telPhone = telPhone;
		this.state = state;
		this.createTime = createTime;
		this.isNew = isNew;
	}

	public User(String userName, String password, String grade, String name,
			String nickName, String telPhone, String email, String qq,
			int state, Date createTime, int isNew, Date lastLoginTime) {
		this.userName = userName;
		this.password = password;
		this.grade = grade;
		this.name = name;
		this.nickName = nickName;
		this.telPhone = telPhone;
		this.email = email;
		this.qq = qq;
		this.state = state;
		this.createTime = createTime;
		this.isNew = isNew;
		this.lastLoginTime = lastLoginTime;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTelPhone() {
		return this.telPhone;
	}

	public void setTelPhone(String telPhone) {
		this.telPhone = telPhone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public int getIsNew() {
		return this.isNew;
	}

	public void setIsNew(int isNew) {
		this.isNew = isNew;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

}
